### ISSUE TITLE
linkschecker

### ISSUE THREAD

**Issue by xmonader** [codescalersinternships/home#69]
create a link checker service in go

### How to run
```
linkscheck --config=config.toml  
```

### configurations (config.toml) 

```toml

[sites]
   [sites.threefold]
     url = threefold.io
   [sites.codescalers]
     url = codescalers.com

```

### behavior

the linkchecker should crawl all of the sites defined in the config and report all of the broken links to stdout 
- link is considered healthy if it responds to head/get requests with 20X or 30X
